Repository FRONTENDBOOTCAMP-13th/Final-12-WhySIBI, pull requests merged in 2025-08, with the labels that each got.

#125 [Refactoring] 메타데이터 추가
  public/image/favicon-dark.ico
  public/image/favicon-light.ico
  src/app/favicon.ico
  src/app/layout.tsx
Labels: ♻️ Refactoring, 🎯 low priority

#127 [Feature] 5가지 카테고리 많이 팔린 상품
  public/image/shopping_banner_image_1.png
  public/image/shopping_banner_image_2.png
  public/image/shopping_banner_image_3.png
  src/app/globals.css
  src/components/Shopping_list/Shopping_banner_card.tsx
  src/components/Shopping_list/Shopping_banner_slider.tsx
  src/components/Shopping_list/Shopping_selling_section.tsx
  src/components/Shopping_list/Shopping_selling_slider.tsx
  src/components/product_search/searching_ui.tsx
Labels: ✨ Feature

#130 [docs] readme.md 초안 작성
  README.md
Labels: 📝 Docs

#148 🐛 fix: 댓글 빌드에러 수정
  src/app/community/[boardType]/[_id]/CommentNew.tsx
Labels: 🐛 Bugfix
